### ISSUE TITLE
'trim' method?

### ISSUE THREAD

**Issue by liz-is** [LTLA/archive-InteractionSet#11]
GenomicInteractions previously had a 'trim' method. 

GInteractions doesn't seem to inherit a 'trim' method from Vector, so GenomicInteractions now doesn't inherit one from GInteractions.

It isn't vital to the GenomicInteractions package but would be nice to have.

**Comment by LTLA** [comment]
What does the `trim` method do in _GenomicInteractions_? If it just trims the anchor regions to fit inside `seqlengths`, then we could do something like:

```
setMethod("trim", "GInteractions", function(x) {
    regions(x) <- trim(regions(x))
    return(x)
})
```

**Comment by liz-is** [comment]
It trims anchors (regions) to seqlengths, as the trim method for GRanges does, and drops interactions involving anchors below a minimum size after trimming. You can see the code used here: https://github.com/ComputationalRegulatoryGenomicsICL/GenomicInteractions/blob/e043a345feca1fdbf353d493ac6f8269f589703b/R/helpers.R#L373

**Comment by LTLA** [comment]
Do you often get situations where you set `minAnchorSize` to a non-unity value? Also, running `trim` on `GenomicRanges` will return all ranges, even if they lie wholly outside `seqlengths` (in which case, they get a zero-length range). It would be good to be consistent with that behaviour, and return all interactions.

**Comment by liz-is** [comment]
To be honest, it's not a function I've used very often. I agree about consistency with GenomicRanges, but then it would be good to have a way to drop interactions involving zero-length ranges.

**Comment by LTLA** [comment]
What about `width` returning a DataFrame of `anchor1` and `anchor2` widths, so you can just do:

```
widths <- width(x)
x <- x[widths$anchor1 & widths$anchor2]
```

Not the most elegant, admittedly, but it'd be close to what you'd do for `GRanges` anyway. Plus, if you did want a minimum anchor width, then you can just ask for that manually in the subsetting operation, rather than making a new argument that not many people would use.

**Comment by liz-is** [comment]
Yep, that makes sense. Does GenomicRanges issue a warning if there are zero-length ranges? I think a warning for interactions involving zero-length ranges would be appropriate. Although likely it would be following shortly after a warning that `'ranges' contains values outside of sequence bounds` that would prompt the trim in the first place...

**Comment by LTLA** [comment]
Well, if there are out-of-range entries, every method in _GenomicRanges_ will complain about it, so I don't think it's something that's easily overlooked. Anyway, I've added `trim` and `width`, so I'm going to close this issue. The only thing that I'll warn you about is that the trimmed regions may be resorted in order to maintain the sorted nature of the `regions` slot - similarly, redundant regions (e.g., if a bunch were out of range) will also be merged into a single entry. This shouldn't cause any drama from an end-user's perspective, as the only change would appear to be trimming of the coordinates of the anchor regions.
