### ISSUE TITLE
overlaps between GInteractions and GRangesList

### ISSUE THREAD

**Issue by liz-is** [LTLA/archive-InteractionSet#12]
Hi,

`overlapsAny(GInteractions, GRangesList)` with a GRangesList longer than 2 doesn't work. Am I missing a way to get overlaps between a GInteractions and a GRangesList without coercing the latter to a GRanges?

**Comment by LTLA** [comment]
Yeah, this was something confusing that I'm thinking of taking out, or modifying. The `GRangesList` overlap is currently set to do 2D overlaps, so it needs to be set to two parallel ranges for the two anchor regions. I'm planning on changing it so that `findOverlaps,GInteractions,Vector-method` will do 1D overlaps for everyone; it should be as easy as switching `GRanges` to `Vector` in the method definition.

**Comment by liz-is** [comment]
Great! 2D overlaps are definitely useful but I think they'd be better off in a different function, otherwise it's confusing, as you said.

**Comment by LTLA** [comment]
Done.
