### ISSUE TITLE
Find the other anchor of the overlapping anchor

### ISSUE THREAD

**Issue by crazyhottommy** [LTLA/archive-InteractionSet#13]
Hi,

Many thanks for developing this package.
one common analysis is to find the other anchor of the overlapping anchor.

```
                first (promoters)                  second
----------|-------------|----------------------|------------|--------   gi

                                                    |------------|        of.interest (enhancers)
```

since `of.interest` overlaps `second`, I want to return `first` in the `gi`.

Is there an easy way to do it?

In the end, I want output like:

`of.interest`    `second`   `first`.

In other words, I want to track which anchor overlaps with the of.interest, and at the same time report the other anchor.

Now, I am doing it below, do you have an easier solution?

``` r
all.regions <- GRanges(rep(c("chrA", "chrB"), c(10, 5)), 
    IRanges(c(0:9*10+1, 0:4*5+1), c(1:10*10, 1:5*5)))
index.1 <- c(5, 15,  3, 12, 9, 10)
index.2 <- c(1,  5, 11, 13, 7,  4) 
gi <- GInteractions(index.1, index.2, all.regions)

of.interest <- GRanges(c("chrA","chrB"), IRanges(start=c(30,3),end=c(50,4)))
olap <- findOverlaps(gi, of.interest)
olap

olap.achors<- anchors(gi[queryHits(olap)])

hits1<- findOverlaps(olap.achors$first, of.interest)
olap.achors$first[queryHits(hits1)]
of.interest[subjectHits(hits1)]

hits2<-findOverlaps(olap.achors$second, of.interest)
olap.achors$second[queryHits(hits2)]
of.interest[subjectHits(hits2)]
```

Thanks!
Ming

**Comment by crazyhottommy** [comment]
I think `linkOverlaps` is what I need..
Thanks.

**Comment by LTLA** [comment]
`linkOverlaps` doesn't quite do what you want to do. The aim of that function is to identify interactions that are "linking" two sets of intervals. For example, if you had a set of enhancers and a set of genes, you could find which interactions were linking which genes to which enhancers. It won't tell you the other (i.e., non-overlapping) anchor region of a interaction that has one anchor region overlapping a region of interest.

The simplest way to do what you want is to set the `use.region` argument:

```
# get overlaps between of.interest and first anchor
hits1 <- findOverlaps(gi, of.interest, use.region="first")
anchors(gi[queryHits(hits1),], type="first") # overlapping
anchors(gi[queryHits(hits1),], type="second") # "other"
of.interest[subjectHits(hits1)]

# get overlaps # between of.interest and second anchor
hits2 <- findOverlaps(gi, of.interest, use.region="second")
anchors(gi[queryHits(hits2),], type="second") # overlapping
anchors(gi[queryHits(hits2),], type="first") # "other"
of.interest[subjectHits(hits2)]
```

It's hard to simplify this into a single function call, because there's so many different aspects of the data that you'll end up having to dig through a list of output objects to extract what you want. The calling sequence above requires a bit of effort but is probably the most flexible and transparent approach.

If you're willing to sacrifice some information, you might consider using the `linearize` method:

```
gi$index <- seq_along(gi)
linearize(gi, of.interest[1])
linearize(gi, of.interest[2])
```

This will return a `GRanges` containing the "other" anchor region for all interactions that overlap each entry in `of.interest` (you can figure out what those interactions were by looking at `index` in the returned object). `linearize` also provides options for handling "internal" interactions where both anchor regions overlap the specified entry of `of.interest`; by default, the union of the two anchor regions is returned for such interactions, but they can be removed entirely by setting `internal=FALSE`.

**Comment by crazyhottommy** [comment]
I am getting errors when using `linearize`

``` r
all.regions <- GRanges(rep("chrA",8), 
    IRanges(c(1,6,2,9,2,5,15,20), c(3,10,4,12,4,7,18,23)))
index.1 <- c(1,3,5,7)
index.2 <- c(2,4,6,8) 
gi <- GInteractions(index.1, index.2, all.regions)

gi

of.interest <- GRanges(c("chrA","chrB"), IRanges(start=c(30,3),end=c(50,4)))

gi$index <- seq_along(gi)
linearize(gi, of.interest[1])
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘linearize’ for signature ‘"GInteractions", "GRanges

```

``` r
> sessionInfo()
R Under development (unstable) (2016-02-23 r70215)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] RBGL_1.47.0                 graph_1.49.1               
 [3] BiocInstaller_1.21.3        InteractionSet_0.99.2      
 [5] SummarizedExperiment_1.1.21 Biobase_2.31.3             
 [7] GenomicRanges_1.23.23       GenomeInfoDb_1.7.6         
 [9] IRanges_2.5.36              S4Vectors_0.9.40           
[11] BiocGenerics_0.17.3        

loaded via a namespace (and not attached):
[1] lattice_0.20-33 grid_3.3.0      zlibbioc_1.17.0 XVector_0.11.7  Matrix_1.2-3   
[6] tools_3.3.0     yaml_2.1.13     knitr_1.12.3  
```

**Comment by LTLA** [comment]
Try updating to the latest version of _InteractionSet_ (0.99.3), I added those methods today.

**Comment by crazyhottommy** [comment]
Thanks! it is working properly now. I am writing down what I have learned so far for all those manipulations. I will share once I got it done.

**Comment by crazyhottommy** [comment]
I wrote a blog post for this http://crazyhottommy.blogspot.com/2016/03/breakpoints-clustering-for-structural.html

Thanks again!
