### ISSUE TITLE
Set arithmetic

### ISSUE THREAD

**Issue by lawremi** [LTLA/archive-InteractionSet#6]
Is there a way to compute the union, intersection, setdiff of an interacting pair? Could be just `pintersect(interactions)` or `punion(interactions)` where the second argument is missing. Perhaps also a convenience for filtering by percent overlap? Like `subsetByOverlaps(interactions, firstFraction = 0.2)`. This makes filtering of overlap hits much easier.

**Comment by LTLA** [comment]
It may be simpler to call the relevant functions on the extracted anchor `GRanges`. There won't be any savings from avoiding redundancy for repeated regions, because this kind of processing has to be performed pair-by-pair anyway. Calling the methods on `GRanges` also makes it more obvious what's being done, as it's not clear what those methods should do for a `GInteractions` object. For example, I can understand the use of `union` to identify the span of the interacting regions, but the `intersect` method seems strange as it won't give anything for the bulk of interactions involving non-overlapping anchor regions. I don't know that I would ever use `setdiff`, either.

**Comment by lawremi** [comment]
Please note that the functions are `*p*intersect`, `*p*union`, etc. The intent is not time savings, per se, but cleaner syntax for operating on overlapping interactions, see #5 .

**Comment by lawremi** [comment]
Closing this, since it falls outside the scope of this package.
